version: '2.4'
services:
    sonarqube:
        container_name: sonarqube
        ports:
            - 9000:9000
        environment:
            - sonar.jdbc.url=jdbc:postgresql://sonar-postgres:5432/sonar
            - sonar.jdbc.username=sonar
            - sonar.jdbc.password=sonar
        volumes:
            - sonarqube_conf:/opt/sonarqube/conf
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_logs:/opt/sonarqube/logs
            - sonarqube_data:/opt/sonarqube/data
        restart: unless-stopped
        image: sonarqube
